DROP TABLE IF EXISTS forward_Data;


CREATE TABLE forward_Data (
  L1 REAL NOT NULL,
  L2 REAL NOT NULL,
  Theta1 REAL NOT NULL,
  Theta2 REAL NOT NULL,
  X REAL NOT NULL,
  Y REAL NOT NULL
);

CREATE TABLE inverse_Data (
  X REAL NOT NULL,
  Y REAL NOT NULL,
  L1 REAL NOT NULL,
  L2 REAL NOT NULL,
  Theta1 REAL NOT NULL,
  Theta2 REAL NOT NULL
);